Terraform 2
Otus-DevOps-2023-07/root31337_infra pull request #12
Opened 2023-09-14 23:06 UTC by root31337

# Выполнено ДЗ №

 - [+ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
-Собраны новые образы в packer
-Сделана разбивка на VM
-Применено использование модулей

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2023-09-15 09:51 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Рекомендую свериться с результатами дз
Нехватает некоторых файлов

2023-09-28 20:46 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Оставил комментарий к файлу =)

2023-09-28 20:46 UTC, mrgreyves commented on terraform/terraform/storage-bucket.tf
> +#tests
Не в той директории файл
И добавьте в конце пустую строку, раз уж решили сделать заглушку =)

2023-10-03 20:03 UTC, root31337 commented
Как победить автотесты? Если убрать описание провайдера, не работает сам терраформ. Если оставить не работают тесты.

2023-10-04 16:24 UTC, root31337 commented
Задания выполнил

2023-10-08 18:26 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все круто =)

2023-10-10 07:04 UTC, merged